use 5.014000;
use ExtUtils::MakeMaker;

WriteMakefile(
	NAME              => 'Zeal',
	VERSION_FROM      => 'lib/Zeal.pm',
	ABSTRACT_FROM     => 'lib/Zeal.pm',
	AUTHOR            => 'Marius Gavrilescu <marius@ieval.ro>',
	MIN_PERL_VERSION  => '5.14.0',
	LICENSE           => 'perl',
	SIGN              => 1,
	PREREQ_PM         => {
		qw/DBI                    0
		   DBD::SQLite            0
		   File::Slurp            0
		   Mac::PropertyList::SAX 0/,
	},
	META_ADD         => {
		dynamic_config => 0,
		resources      => {
			repository   => 'http://git.ieval.ro/?p=zeal.git',
		},
	}
);
